[project]
name = "dlsite-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "colorlog>=6.9.0",
    "japanize-matplotlib>=1.1.3",
    "matplotlib>=3.10.0",
    "mecab-python3>=1.0.10",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
    "unidic-lite>=1.0.8",
    "wordcloud>=1.9.4",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
